remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome: welcome/intro.md
  - Tapis V3 introduction and V2 changes: 
    - Introduction to Tapis and current state: block1/TapisIntro.md 
    - Overview of V3 APIs
    - Changes from V2
  - Tapis V3 design deep dive and roadmap: 
    - Tapis component organization and tenancy: block1/
    - Security Kernel and remote site/data-center deployments: block1/
    - Container support: block1
  - Tapis v3 demo: block2/
  - Tapis early adopter use cases lightning talks:
    - Machine Learning workflow: block2/
    - Precipitation workflow and data science: block2/
    - iReceptor: block2/
    - Remote site/data-center use case: block2/
  - Contributing to Tapis:
    - Tools & best practices: block2/
    - Trainings and code of conduct: block2/