remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Home: ''
  - Welcome to PEARC20: welcome/intro
  - Tapis V3 introduction and V2 changes: block1/TapisIntro 
  - Invited Speaker Scott Christly: 
  - Tapis tenancy and authorization: block1/Tenants
  - Distributed Security: block1/SKIntro 
  - Streaming data: block1/StreamsIntro 
  - Invited Speaker Jack Smith: block2/WQIntro 
  - Invited Speaker Matthew P. Lucas: block2/UH
  - Container support: block2/ContainersIntro
  - Tapis V3 demo: block2/demo 
  - Contributing to Tapis: block2/coc 

theme: jekyll-theme-hacker