remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome and Background:
    - Welcome : ''
  - Tapis V3 introduction and V2 changes
    - Introduction to Tapis and current state: block1/TapisIntro 
  - Tapis V3 design deep dive and roadmap
    - Tapis component organization and tenancy
    - Security Kernel and remote site/data-center deployments: block1/SKIntro
    - Streaming data block1/StreamsIntro
    - Container support
  - Tapis V3 demo: block2/demo
  - Tapis early adopter use cases lightning talks:
    - Machine Learning workflow: 
    - Precipitation workflow and data science: 
    - iReceptor: 
    - Remote site/data-center use case: 
  - Contributing to Tapis:
    - Tools & best practices: 
    - Trainings and code of conduct: 

