remote_theme: marella/jekyll-theme-documentation
#remote_theme: pawamoy/jekyll-readthedocs

#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

permalink: pretty
nav:
  - Welcome to PEARC20: welcome/intro
  - Tapis V3 introduction and V2 changes: block1/TapisIntro 
  - Invited Speaker (Scott C.) 
  - Tapis component organization and tenancy 
  - Distributed Security: block1/SKIntro 
  - Streaming data: block1/StreamsIntro 
  - Innvited Speaker (Jack Smith): block2/WQIntro 
  - Container support: block2/ContainersIntro
  - Tapis V3 demo: block2/demo 
  - Contributing to Tapis: block2/coc 

